enum TypeView { WAITING, NORMAL, TIMEOUT, ERROR, SERVICE_UNAVAILABLE }

enum TypeSectionView { WAITING, NORMAL, TIMEOUT, ERROR, EMPTY }
enum TypeScreenView {
  WAITING,
  NORMAL,
  TIMEOUT,
  ERROR,
  EMPTY,
  NOCONNECTIVITY,
  SERVICE_UNAVAILABLE
}

enum PermissionScreenView {
  NORMAL,
  WARNING,
  SETTINGS,
}

enum TypeResponseNetwork {
  TIMEOUT,
  NOCONNECTIVITY,
  ERROR,
  BAD_RESPONSE,
  SERVICE_UNAVAILABLE
}

enum TypeTransfer {
  TRANSFER_BENEFICIARY,
  TRANSFER_BENEFICIARY_OTHER_BANK,
  TRANSFER_SAME_CUSTOMER,
}

enum TypeTransferFcm {
  TRANSFER_SAME_BANK,
  TRANSFER_SAME_CUSTOMER,
  TRANSFER_OTHER_BANK
}

enum OperationType {
  TRADE_TRANSFER,
  TRANSFER,
  MONEY_ORDER,
  LOCAL_MONEY_ORDER,
  BANK_PAYMENT,
  QR_PAYMENT,
  SERVICE_PAYMENT,
  SERVICE_PAYMENT_IMPROVED,
  DEBIT_AUTHORIZATION,
  CUSTOMER_DATA_ACCESS,
  CUSTOMER_DATA_UPDATE,
  AUTHORIZATION,
  ADD_BENEFICIARY_SB,
  ADD_BENEFICIARY_OB,
  EDIT_BENEFICIARY,
  CARD_CASH_ADVANCE,
  CARD_INTERNET_ENABLE,
  CARD_INTERNET_DISABLE,
  CARD_DEBIT_LIMIT,
  CARD_STATUS_CHANGE,
  CARD_SALE_NEW_DEBIT_CARD,
  LOAN_DISBURSING,
  MOVILINK_REGISTER,
  GENERATE_NEW_ONBOARDING_CLIENT,
  NEW_ACCOUNT,
  GENERATE_OWNERSHIP,
  CHANGE_USER_PASS,
  COBALT_INSURANCE_SALE,
  NONE,
}

enum TypeAccount { CCCA, PR, DPF, TC, TD, TPP }

enum TypeCompany { COMMUNICATION, BASIC, EDUCATION, TAXES, OTHERS, RECHARGES }

enum TypeDelivery { ADDRESS, BANKOFFICE, NONE }

enum MapTabOption { ATM, OFFICE, ALL }

enum ATMFilter { ALL, USD, DEPOSIT }

enum OfficeFilter {
  ALL,
}
enum LoanAccountStatus { ACTIVE, DELAYED, EXPIRED, EXECUTE, OTHER }

enum FullaccessType { AUTHORIZER_DEVICE, SMS_EMAIL, IN_OFFICE }

enum FCMEvent { ON_MESSAGE, ON_RESUME, ON_LAUNCH }
enum FCMType {
  AUTH_CODE,
  BANK_ACTIVITY,
  BANK_MESSAGE,
  AUTH_CODE_FULLACCESS_DEVICE,
  AUTH_CODE_BANK_TRANSACTION,
  AUTHORIZATION_REQUEST,
  NONE,
}

enum AppClient {
  BANECO,
  BANKIO,
  LA_PRIMERA,
  TU_BANCO,
  BANCO_SOL,
  IDEPRO,
}

enum FormFieldType {
  STRING,
  TEXT,
  INTEGER,
  MONEY,
  DECIMAL,
  BOOLEAN,
  DATE,
  TIME,
  SELECTOR,
  SETLECTOR_DOCIDTYPE,
  SELECTOR_BRANCHES,
  SELECTOR_OFFICES,
  SELECTOR_CUSTOM,
  CURRENCY_CUSTOM,
  SEPARATOR,
  NONE,
}

enum ButtonAction {
  NEXT,
  BACK,
  UNKNOWN,
}

enum AuthorizationFilter {
  WAITING_FOR_ME,
  WAITING_FOR_ANYBODY,
  STARTED_BY_ME,
}

enum CameraMaskType {
  SQUARE_MASK,
  RECTANGLE_ID,
  RECTANGLE_ID_PORTRAIT,
  DYNAMIC_RATIO,
  NONE,
}

enum BottomTabs {
  ACCOUNTS_TAB,
  NEW_TRANSFER_TAB,
  BENEFICIARIES_TAB,
  SERVICE_PAYMENTS,
  MONEY_ORDER_TAB,
  LOCALIZATION_TAB,
  NOTIFICATIONS_TAB,
  EXPRESS_LOAN_TAB,
  AUTHORIZER_TAB,
  NONE
}

enum SignUpSelectionNavigationType {
  APP_START,
  LOGIN,
}

enum CardStatus {
  BLOCKED_CARD,
  UNBLOCKED_CARD,
  ACTIVE_CARD,
  OTHER,
}

enum GlobalUIState {
  NORMAL,
  LOADING,
  WAITING_AUTHCODE,
}

enum FaceRecognitionState {
  INITIAL,
  DETECTING,
  DELAYING,
  DONE,
}

enum FaceRecognitionType {
  REGULAR,
  EYES_CLOSED,
}

enum MessageType {
  INFO,
  SUCCESS,
}

enum LoginStatus {
  CHANGE_PASSWORD,
  CHANGE_USER_PASSWORD,
  NONE,
}

enum HelpTab {
  FAQ,
  CONTACT,
}

enum PaymentsTab {
  SERVICE_PAYMENTS,
  DEBIT_AUTHORIZATION,
}

enum TransfersTab {
  TRANSFER,
  BENEFICIARIES,
  SIMPLE,
}

enum ServiceCompany {
  FIREBASE,
  HUAWEI,
}

enum ServiceState {
  NONE,
  ERROR_INITIALAZING,
  INITIALIZED_SUCCESSFULLY,
}

enum UniversalMapType {
  SATELLITE,
  NORMAL,
}

enum ModifyType {
  DELETE,
  UPDATE,
}
enum SimpleOptions {
  SCAN,
  GALLERY,
  SIMPLE_TAB,
  GENERATE_QR,
}

enum AuthCodeType {
  PUSH_NOTIFICATION,
  SMS,
  EMAIL,
  OTHER,
}

enum RecentActivityType {
  OPERATION,
  TRANSACTION,
  INVOICE,
  NONE,
}

enum FileExportFormat { XLSX, PDF, CSV, MT940 }

enum AppScreen {
  DASHBOARD,
  BENEFICIARY_DEATILS,
  DEBIT_AUTHORIZATION_DETAILS,
  OTHER,
}

enum ScreenActions { REFRESH_DATA, UNKNOWN }
