name: baneco
description: Viridian Digital Bank project for Baneco.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.2080+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # camera: ^0.9.4
  camera: ^0.9.4+5
  path: ^1.8.0
  flutter_localizations:
    sdk: flutter
  firebase_ml_vision: 0.9.9
  firebase_messaging: ^10.0.2
  firebase_core: ^1.3.0
  google_maps_flutter: ^2.0.11
  apple_maps_flutter: ^1.0.0
  image_picker: ^0.8.4+4
  flutter_icons: ^1.0.0+1
  # sentry_flutter: ^5.0.0
  
  location: ^4.3.0
  geolocator: ^8.0.1
  flutter_math_fork: ^0.6.0
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  path_provider: ^2.0.1
  intl: ^0.17.0
  sqflite: ^2.0.0+3
  http: ^0.13.3
  package_info: ^2.0.0
  device_info: ^2.0.1
  connectivity: ^3.0.4
  encrypt: ^5.0.0
  crypt: ^4.0.1
  convert: ^3.0.0
  auto_size_text: ^2.1.0
  mime: ^1.0.0
  launch_review: ^3.0.1

  # appspector: ^0.8.1

  shared_preferences: ^2.0.5
  barcode_scan2: ^4.2.0
  qr: ^2.0.0
  share_extend: ^2.0.0
  image_gallery_saver: ^1.7.0
  
  font_awesome_flutter: ^9.0.0
  flutter_typeahead: ^3.2.0
  pull_to_refresh: ^2.0.0
  local_auth: ^1.1.5

  image_editor: ^1.0.0
  extended_image: ^4.1.0
  heic_to_jpg: ^0.2.0

  url_launcher: ^6.0.4
  flutter_secure_storage: ^4.2.0
  flutter_keyboard_visibility: ^5.0.2
  flutter_native_image: ^0.0.6
  contacts_service: ^0.6.1
  audioplayers: ^0.19.0
  open_file: ^3.2.1
  flutter_svg: ^1.0.0
  image: ^3.0.2
  safe_device: ^1.0.8
  exif: ^2.2.0 
  image_crop: ^0.4.0
  sticky_headers: ^0.2.0
  advertising_id: ^2.0.0

  receive_sharing_intent: ^1.4.5

  in_app_review: ^2.0.2

  share_plus: ^3.0.4

  permission_handler: ^8.0.0+2
  animations: ^2.0.1
  device_apps: ^2.1.1
  flutter_html: ^3.0.0-alpha.2
  flutter_html_table: ^3.0.0-alpha.2
  extended_masked_text: ^2.3.1
  month_picker_dialog: ^0.4.0
  
  dartz: ^0.9.2


  selphi_face_plugin:
    path: plugins/selphi_face_plugin/
  selphid_plugin:
    path: plugins/selphid_plugin/
  flutter_cupertino_date_picker:
    path: plugins/flutter_cupertino_date_picker-1.0.12/
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter_icons:
#   android: true
#   ios: true
#   image_path_ios: "assets/allContent/logo.jpg"
#   image_path_android: "assets/allContent/logo.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: BanecoIcons
      fonts:
        - asset: fonts/BanecoIcons.ttf

    - family: BancoSolIcons
      fonts:
        - asset: fonts/BancoSolIcons.ttf

    - family: Din
      fonts:
        - asset: fonts/d-din-regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/allContent/banklogo_baneco.png
    # - assets/allContent/banklogo_bankio.png
    # - assets/allContent/banklogo_bsol.png
    # - assets/allContent/banklogo_bsol2.png
    # - assets/allContent/banklogo_bankiowhite.png
    - assets/allContent/simple70_black_white.png
    - assets/allContent/simple_black_background_50x50.png
    - assets/allContent/simple_black_background_baneco_50x50.png
    # - assets/allContent/simple_black_background_bankio_50x50.png
    # - assets/allContent/simple_black_background_bsol_50x50.png
    - assets/allContent/icono_check.png
    - assets/allContent/icono_check_orange.png
    - assets/allContent/icono_pregunta.png
    # - assets/allContent/atm_size_1.png
    # - assets/allContent/office_size_1.png
    # - assets/allContent/atm_size_2.png
    # - assets/allContent/office_size_2.png
    # - assets/allContent/atm_android_size1.png
    # - assets/allContent/atm_ios_size1.png
    # - assets/allContent/office_android_size1.png
    # - assets/allContent/office_ios_size1.png
    - assets/allContent/atm_android_size1_red.png
    - assets/allContent/atm_ios_size1_red.png
    - assets/allContent/office_android_size1_red.png
    - assets/allContent/office_ios_size1_red.png
    # - assets/allContent/atm_android_size1_blue.png
    # - assets/allContent/atm_ios_size1_blue.png
    # - assets/allContent/office_android_size1_blue.png
    # - assets/allContent/office_ios_size1_blue.png
    # - assets/allContent/background_soft_4.jpg
    # - assets/allContent/background_soft_5.jpg
    # - assets/allContent/background_soft_6.jpg
    # - assets/allContent/boton_ganasol.png
    - assets/allContent/svg/back_ci_baneco.svg
    - assets/allContent/svg/front_ci_baneco.svg
    - assets/allContent/svg/selfie_baneco.svg
    - assets/allContent/svg/signature_baneco.svg
    - assets/allContent/card_chip.png
    - assets/allContent/card_corner.png
    - assets/allContent/visa_logo.jpg
    - assets/allContent/contactless-payment.png
    - assets/audio/shutter_camera.aac
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
