/// Flutter icons BancoSolIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BancoSolIcons
///      fonts:
///       - asset: fonts/BancoSolIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BancoSolIcons {
  BancoSolIcons._();

  static const _kFontFam = 'BancoSolIcons';
  static const _kFontPkg = null;

  static const IconData location_frame = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pagos_frame = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transferencias_frame = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData simple_frame = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData geolocation_frame = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_bell_frame = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_frame = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light_frame = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taxes_build_frame = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cellphone_reload_frame = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_order_frame = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt_frame = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schedule_frame = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData international_money_order_frame = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData change_amounts_frame = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData historic_extract_frame = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taxes_frame = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_center_frame = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData claim_point = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData atm_frame = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payment_plan_frame = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disbursement_receipt_frame = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credits_contract_frame = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_tracking_frame = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout_frame = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_payment_frame = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscriber_registration_frame = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_purchase_frame = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password_change__frame = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password_change_alt_frame = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact_frame = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData secure_frame = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login_frame = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news_frame = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData online_product_request_frame = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block_card_frame = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_center_frame = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData atm_alt_frame = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData savings_account_frame = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData device_change_frame = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tax_window_frame = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block_card_alt_frame = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sol_amigo_frame = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert_frame = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credits_payment_frame = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData national_money_order_frame = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData savings_account_alt_frame = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credits_frame = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card_limit_frame = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loan_express_frame = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_services_frame = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transaction_code_frame = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData service_payment_alt_frame = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transfers_alt_frame = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData last_payments_frame = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inicio_frame = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_operations_frame = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_operations_alt = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inicio = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password_change_alt = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password_change = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_center = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_bell = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pagos = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscriber_registration = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_tracking = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData online_product_request = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schedule = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transferencias = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData historic_extract = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_payment = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_purchase = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payment_plan = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credits_contract = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disbursement_receipt = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData device_change = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData savings_account = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password_change_alt_2 = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card_limit = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block_card_alt = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transaction_code = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_center = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_order = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taxes = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cellphone_reload = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_services = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credits_payment = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData secure = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData change_amounts = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block_card = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData international_money_order = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData national_money_order = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transfers_alt = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData last_payments = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credits = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData savings_account_alt = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData simple = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tax_window = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData atm_alt = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taxes_build_frame_1 = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loan_express = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loan_express_alt = IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData atm = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData geolocation = IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData service_payment_alt = IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login = IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_operations = IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pago_de_servicios = IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData public_services = IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_services_alt = IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payment_services_basic = IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData service_payment_tab = IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
