/// Flutter icons BanecoIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BanecoIcons
///      fonts:
///       - asset: fonts/BanecoIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BanecoIcons {
  BanecoIcons._();

  static const _kFontFam = 'BanecoIcons';
  static const String _kFontPkg = null;

  static const IconData inicio = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_bell = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData geolocation = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pagos = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transferencias = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData simple = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_right = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData school = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taxes_build = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cellphone_reload = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData face_id = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_order = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transfer_and_qr = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exchange_rate = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apps = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData movilink = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loan = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
